# Generated by Django 2.0.7 on 2018-08-09 14:25

import TaskManager.myForm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='day',
            field=TaskManager.myForm.DayOfTheWeekField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
