# Generated by Django 2.0.7 on 2018-08-09 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20180809_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='type',
            new_name='task_type',
        ),
    ]
