# Generated by Django 2.0.7 on 2018-08-01 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailActivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('key', models.CharField(blank=True, max_length=120, null=True, verbose_name='key')),
                ('forced_expired', models.BooleanField(default=False)),
                ('expires', models.IntegerField(default=7)),
                ('activated', models.BooleanField(default=False, verbose_name='Act')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Update time')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email field')),
                ('full_name', models.CharField(blank=True, max_length=254, null=True, verbose_name='Full name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active flag')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Registration time')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='emailactivation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User', verbose_name='User'),
        ),
    ]
